// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for bio documents
 */
interface BioDocumentData {
  /**
   * Profile Image field in *bio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.profile_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_image: prismic.ImageField<never>;

  /**
   * Bio Text field in *bio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.bio_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio_text: prismic.RichTextField;

  /**
   * Current Location field in *bio*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: bio.current_location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  current_location: prismic.GeoPointField;
}

/**
 * bio document from Prismic
 *
 * - **API ID**: `bio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BioDocumentData>, "bio", Lang>;

type BlogPostDocumentDataBodySlice = TextSlice | CodeSlice | ImageSlice;

/**
 * Primary content in *blog-post → Slice Zone → General Card → Primary*
 */
export interface BlogPostDocumentDataSocialGeneralCardSlicePrimary {
  /**
   * Title field in *blog-post → Slice Zone → General Card → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title...
   * - **API ID Path**: blog-post.social[].general_card.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *blog-post → Slice Zone → General Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description...
   * - **API ID Path**: blog-post.social[].general_card.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *blog-post → Slice Zone → General Card → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog-post.social[].general_card.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Slice for *blog-post → Slice Zone*
 */
export type BlogPostDocumentDataSocialGeneralCardSlice = prismic.Slice<
  "general_card",
  Simplify<BlogPostDocumentDataSocialGeneralCardSlicePrimary>,
  never
>;

/**
 * Primary content in *blog-post → Slice Zone → Twitter Card → Primary*
 */
export interface BlogPostDocumentDataSocialTwitterCardSlicePrimary {
  /**
   * Card type field in *blog-post → Slice Zone → Twitter Card → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Standard Summary Card
   * - **API ID Path**: blog-post.social[].twitter_card.primary.card_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_type: prismic.SelectField<
    "Standard Summary Card" | "Summary Card with Large Image",
    "filled"
  >;

  /**
   * Twitter Handle field in *blog-post → Slice Zone → Twitter Card → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Twitter handle...
   * - **API ID Path**: blog-post.social[].twitter_card.primary.twitter_handle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  twitter_handle: prismic.KeyTextField;

  /**
   * Title field in *blog-post → Slice Zone → Twitter Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Twitter Card Title...
   * - **API ID Path**: blog-post.social[].twitter_card.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *blog-post → Slice Zone → Twitter Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Twitter Card Description...
   * - **API ID Path**: blog-post.social[].twitter_card.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *blog-post → Slice Zone → Twitter Card → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog-post.social[].twitter_card.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"large_image">;
}

/**
 * Slice for *blog-post → Slice Zone*
 */
export type BlogPostDocumentDataSocialTwitterCardSlice = prismic.Slice<
  "twitter_card",
  Simplify<BlogPostDocumentDataSocialTwitterCardSlicePrimary>,
  never
>;

/**
 * Primary content in *blog-post → Slice Zone → Pinterest Product Pin → Primary*
 */
export interface BlogPostDocumentDataSocialPinterestProductPinSlicePrimary {
  /**
   * Title field in *blog-post → Slice Zone → Pinterest Product Pin → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title...
   * - **API ID Path**: blog-post.social[].pinterest_product_pin.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *blog-post → Slice Zone → Pinterest Product Pin → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description...
   * - **API ID Path**: blog-post.social[].pinterest_product_pin.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Price field in *blog-post → Slice Zone → Pinterest Product Pin → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Enter Product Price...
   * - **API ID Path**: blog-post.social[].pinterest_product_pin.primary.price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Currency field in *blog-post → Slice Zone → Pinterest Product Pin → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: USD
   * - **API ID Path**: blog-post.social[].pinterest_product_pin.primary.currency
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  currency: prismic.SelectField<"USD" | "Euro", "filled">;

  /**
   * Availability field in *blog-post → Slice Zone → Pinterest Product Pin → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: In-stock
   * - **API ID Path**: blog-post.social[].pinterest_product_pin.primary.availability
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  availability: prismic.SelectField<"In-stock" | "Out of stock", "filled">;
}

/**
 * Slice for *blog-post → Slice Zone*
 */
export type BlogPostDocumentDataSocialPinterestProductPinSlice = prismic.Slice<
  "pinterest_product_pin",
  Simplify<BlogPostDocumentDataSocialPinterestProductPinSlicePrimary>,
  never
>;

type BlogPostDocumentDataSocialSlice =
  | BlogPostDocumentDataSocialGeneralCardSlice
  | BlogPostDocumentDataSocialTwitterCardSlice
  | BlogPostDocumentDataSocialPinterestProductPinSlice;

/**
 * Content for blog-post documents
 */
interface BlogPostDocumentData {
  /**
   * Slice Zone field in *blog-post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog-post.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<BlogPostDocumentDataBodySlice> /**
   * headline field in *blog-post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: My new blogpost
   * - **API ID Path**: blog-post.headline
   * - **Tab**: Overview
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  headline: prismic.TitleField;

  /**
   * thumbnail field in *blog-post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog-post.thumbnail
   * - **Tab**: Overview
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * description field in *blog-post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Add description for overview
   * - **API ID Path**: blog-post.description
   * - **Tab**: Overview
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField /**
   * Slice Zone field in *blog-post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog-post.social[]
   * - **Tab**: Social Cards
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  social: prismic.SliceZone<BlogPostDocumentDataSocialSlice>;
}

/**
 * blog-post document from Prismic
 *
 * - **API ID**: `blog-post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog-post",
    Lang
  >;

type DefaultPageDocumentDataSlicesSlice = TextSlice;

/**
 * Content for Default documents
 */
interface DefaultPageDocumentData {
  /**
   * Slice Zone field in *Default*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DefaultPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Default*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: default_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Default*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Default*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: default_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Default document from Prismic
 *
 * - **API ID**: `default_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DefaultPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DefaultPageDocumentData>,
    "default_page",
    Lang
  >;

/**
 * Item in *footer navigation → Menu Links*
 */
export interface FooterNavigationDocumentDataMenuLinksItem {
  /**
   * Link Label field in *footer navigation → Menu Links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Link Label...
   * - **API ID Path**: footer_navigation.menu_links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *footer navigation → Menu Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a Link...
   * - **API ID Path**: footer_navigation.menu_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for footer navigation documents
 */
interface FooterNavigationDocumentData {
  /**
   * `title` field in *footer navigation*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Menu title...
   * - **API ID Path**: footer_navigation.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Menu Links field in *footer navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.menu_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_links: prismic.GroupField<
    Simplify<FooterNavigationDocumentDataMenuLinksItem>
  >;
}

/**
 * footer navigation document from Prismic
 *
 * - **API ID**: `footer_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterNavigationDocumentData>,
    "footer_navigation",
    Lang
  >;

type HomeDocumentDataSlicesSlice = LatestBlogPostsSlice | HomeHeaderSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Homepage Intro → gallery*
 */
export interface HomepageIntroDocumentDataGalleryItem {
  /**
   * Image 1 field in *Homepage Intro → gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_intro.gallery[].image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Homepage Intro → gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_intro.gallery[].image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *Homepage Intro → gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_intro.gallery[].image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *Homepage Intro → gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_intro.gallery[].image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;

  /**
   * Image 5 field in *Homepage Intro → gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_intro.gallery[].image_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_5: prismic.ImageField<never>;
}

/**
 * Content for Homepage Intro documents
 */
interface HomepageIntroDocumentData {
  /**
   * Headline field in *Homepage Intro*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_intro.headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * Description field in *Homepage Intro*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_intro.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * gallery field in *Homepage Intro*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_intro.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<HomepageIntroDocumentDataGalleryItem>>;
}

/**
 * Homepage Intro document from Prismic
 *
 * - **API ID**: `homepage_intro`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageIntroDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageIntroDocumentData>,
    "homepage_intro",
    Lang
  >;

/**
 * Content for project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Link field in *project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Readable URL field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.readable_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  readable_url: prismic.KeyTextField;
}

/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes =
  | BioDocument
  | BlogPostDocument
  | DefaultPageDocument
  | FooterNavigationDocument
  | HomeDocument
  | HomepageIntroDocument
  | ProjectDocument;

/**
 * Primary content in *Code → Primary*
 */
export interface CodeSliceDefaultPrimary {
  /**
   * code field in *Code → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: code.primary.code
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  code: prismic.RichTextField;

  /**
   * Language field in *Code → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: js
   * - **API ID Path**: code.primary.language
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  language: prismic.SelectField<
    "js" | "ts" | "css" | "json" | "html" | "vue" | "vue-html",
    "filled"
  >;
}

/**
 * Default variation for Code Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CodeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Code*
 */
type CodeSliceVariation = CodeSliceDefault;

/**
 * Code Shared Slice
 *
 * - **API ID**: `code`
 * - **Description**: Code
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeSlice = prismic.SharedSlice<"code", CodeSliceVariation>;

/**
 * Primary content in *HomeHeader → Primary*
 */
export interface HomeHeaderSliceDefaultPrimary {
  /**
   * headline field in *HomeHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is a headline
   * - **API ID Path**: home_header.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * description field in *HomeHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A meaningful description
   * - **API ID Path**: home_header.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *HomeHeader → Items*
 */
export interface HomeHeaderSliceDefaultItem {
  /**
   * image field in *HomeHeader → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_header.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HomeHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeaderSliceDefaultPrimary>,
  Simplify<HomeHeaderSliceDefaultItem>
>;

/**
 * Slice variation for *HomeHeader*
 */
type HomeHeaderSliceVariation = HomeHeaderSliceDefault;

/**
 * HomeHeader Shared Slice
 *
 * - **API ID**: `home_header`
 * - **Description**: HomeHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeaderSlice = prismic.SharedSlice<
  "home_header",
  HomeHeaderSliceVariation
>;

/**
 * Primary content in *Image → Items*
 */
export interface ImageSliceDefaultItem {
  /**
   * Image field in *Image → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageSliceDefaultItem>
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Default variation for LatestBlogPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestBlogPostsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *LatestBlogPosts*
 */
type LatestBlogPostsSliceVariation = LatestBlogPostsSliceDefault;

/**
 * LatestBlogPosts Shared Slice
 *
 * - **API ID**: `latest_blog_posts`
 * - **Description**: LatestBlogPosts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestBlogPostsSlice = prismic.SharedSlice<
  "latest_blog_posts",
  LatestBlogPostsSliceVariation
>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BioDocument,
      BioDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataBodySlice,
      BlogPostDocumentDataSocialGeneralCardSlicePrimary,
      BlogPostDocumentDataSocialTwitterCardSlicePrimary,
      BlogPostDocumentDataSocialPinterestProductPinSlicePrimary,
      BlogPostDocumentDataSocialSlice,
      DefaultPageDocument,
      DefaultPageDocumentData,
      DefaultPageDocumentDataSlicesSlice,
      FooterNavigationDocument,
      FooterNavigationDocumentData,
      FooterNavigationDocumentDataMenuLinksItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HomepageIntroDocument,
      HomepageIntroDocumentData,
      HomepageIntroDocumentDataGalleryItem,
      ProjectDocument,
      ProjectDocumentData,
      AllDocumentTypes,
      CodeSlice,
      CodeSliceDefaultPrimary,
      CodeSliceVariation,
      CodeSliceDefault,
      HomeHeaderSlice,
      HomeHeaderSliceDefaultPrimary,
      HomeHeaderSliceDefaultItem,
      HomeHeaderSliceVariation,
      HomeHeaderSliceDefault,
      ImageSlice,
      ImageSliceDefaultItem,
      ImageSliceVariation,
      ImageSliceDefault,
      LatestBlogPostsSlice,
      LatestBlogPostsSliceVariation,
      LatestBlogPostsSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
    };
  }
}
