// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  code: defineAsyncComponent(() => import("./Code/index.vue")),
  home_header: defineAsyncComponent(() => import("./HomeHeader/index.vue")),
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  latest_blog_posts: defineAsyncComponent(
    () => import("./LatestBlogPosts/index.vue"),
  ),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
});
