// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from 'vue'
import { defineSliceZoneComponents } from '@prismicio/vue'

export const components = defineSliceZoneComponents({
  home_header: defineAsyncComponent(() => import('./HomeHeader/index.vue')),
  latest_blog_posts: defineAsyncComponent(
    () => import('./LatestBlogPosts/index.vue'),
  ),
  code: defineAsyncComponent(() => import('./Code/index.vue')),
  image: defineAsyncComponent(() => import('./Image/index.vue')),
  text: defineAsyncComponent(() => import('./Text/index.vue')),
})
